### PR TITLE
[*] MO : Implements styles for new brand.

### PR DESCRIPTION
**Pull request by jgarzonp**
PayU Rebranding

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @jgarzonp,

Can you please rebase your PR in order to have only one commit with this title ? :)

Thanks

**Comment by jgarzonp** [comment]
Hi @Quetzacoalt91,

I did the rebase from all previous commits made by me to the last commit (1ba91ad),  but I do not know if that gives solution to your request.

**Comment by Quetzacoalt91** [comment]
Hi @jgarzonp,

What about for already installed instances ? Do you want to update their order status to remove "Latam" in the name ?

**Comment by jgarzonp** [comment]
Hi @Quetzacoalt91,

Yes, the idea is to update all the instances to the new brand, with the new colors and the logo, and obviously, the brand name, that it is now just "PayU", without the "Latam" word.

**Comment by Quetzacoalt91** [comment]
So I guess you will have to execute an upgrade file for your module, which will load the existing order status related to PayU, update their name and save them.

You can have more information here: http://doc.prestashop.com/display/PS15/Auto-updating+modules

**Comment by jgarzonp** [comment]
Sorry, I think that I didn't express myself in the right way, the change is related just to the look and feel, the constants and parameters about the process did not change. The old data stored in database should not be affected and the process must continue like usual.

**Comment by Quetzacoalt91** [comment]
Hi @jgarzonp,

Thanks, your PR has just been merged and the changes should be available from tomorrow.

Best regards

**Pull request merged**
